#!/usr/bin/env node
// stats-compass 프로젝트 파일 자동 생성 스크립트
// 사용법:  node setup.mjs
// 실행 후: .env 파일에 KOSIS_API_KEY, SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY 설정
//        pnpm install (또는 npm install)
//        pnpm seed:all

import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname } from 'node:path';

const files = {
  ".gitignore": "node_modules/\n.env\n.env.local\ndata/seed/*.json\n!data/seed/.gitkeep\ndist/\n.DS_Store\n*.log\n",
  ".env.example": "KOSIS_API_KEY=your_kosis_key\nSUPABASE_URL=https://your-project.supabase.co\nSUPABASE_SERVICE_ROLE_KEY=sb_secret_xxx\nKOSIS_ORG_ID=101\nSEED_CONCURRENCY=3\n",
  "package.json": "{\n  \"name\": \"stats-compass\",\n  \"version\": \"0.1.0\",\n  \"description\": \"통계나침반 - 국가승인통계 큐레이션 페이지\",\n  \"private\": true,\n  \"type\": \"module\",\n  \"engines\": {\n    \"node\": \">=20.0.0\"\n  },\n  \"scripts\": {\n    \"typecheck\": \"tsc --noEmit\",\n    \"seed:tables\": \"tsx src/seed/01_fetchTables.ts\",\n    \"seed:meta\": \"tsx src/seed/02_fetchMeta.ts\",\n    \"seed:build\": \"tsx src/seed/03_buildStatistics.ts\",\n    \"seed:upsert\": \"tsx src/seed/04_upsertSupabase.ts\",\n    \"seed:all\": \"pnpm seed:tables && pnpm seed:meta && pnpm seed:build && pnpm seed:upsert\"\n  },\n  \"dependencies\": {\n    \"@supabase/supabase-js\": \"^2.45.0\",\n    \"dotenv\": \"^16.4.5\",\n    \"p-limit\": \"^6.1.0\"\n  },\n  \"devDependencies\": {\n    \"@types/node\": \"^22.7.0\",\n    \"tsx\": \"^4.19.0\",\n    \"typescript\": \"^5.6.0\"\n  }\n}\n",
  "tsconfig.json": "{\n  \"compilerOptions\": {\n    \"target\": \"ES2022\",\n    \"module\": \"ESNext\",\n    \"moduleResolution\": \"Bundler\",\n    \"esModuleInterop\": true,\n    \"allowSyntheticDefaultImports\": true,\n    \"strict\": true,\n    \"skipLibCheck\": true,\n    \"resolveJsonModule\": true,\n    \"isolatedModules\": true,\n    \"noEmit\": true,\n    \"types\": [\n      \"node\"\n    ]\n  },\n  \"include\": [\n    \"src/**/*.ts\"\n  ],\n  \"exclude\": [\n    \"node_modules\",\n    \"dist\"\n  ]\n}\n",
  "data/seed/.gitkeep": "",
  "src/types.ts": "// KOSIS 응답 타입 및 내부 정제 타입\n\nexport interface KosisListItem {\n  LIST_ID?: string;\n  LIST_NM?: string;\n  ORG_ID?: string;\n  TBL_ID?: string;\n  TBL_NM?: string;\n  STAT_NM?: string;\n  VW_CD?: string;\n  SEQ_NO?: string;\n  LINK_URL?: string;\n  UP_LIST_ID?: string;\n  FULL_PATH_ID?: string;\n}\n\nexport interface KosisTableMeta {\n  ORG_ID: string;\n  ORG_NM?: string;\n  TBL_ID: string;\n  TBL_NM: string;\n  STAT_NM?: string;\n  MAINC_NM?: string;\n  COLLECT_CYCLE?: string;\n  PRP_CNT?: string;\n  LAWFUL_BAS?: string;\n  STATS_TARGET?: string;\n  RESN_TXT?: string;\n  UPDATE_DT?: string;\n  START_PRD_DE?: string;\n  END_PRD_DE?: string;\n}\n\nexport interface CollectedTable {\n  org_id: string;\n  tbl_id: string;\n  tbl_nm: string;\n  stat_nm: string;\n  category_path: string;\n  full_path_id?: string;\n  link_url?: string;\n}\n\nexport interface EnrichedTable extends CollectedTable {\n  meta?: KosisTableMeta;\n  meta_error?: string;\n}\n\nexport interface BuiltStatistic {\n  stat_id: string;\n  stat_nm: string;\n  agency: string;\n  org_id: string;\n  category: string;\n  legal_basis?: string;\n  purpose?: string;\n  target?: string;\n  method?: string;\n  frequency?: string;\n  tables: {\n    kosis_org_id: string;\n    kosis_tbl_id: string;\n    table_name: string;\n    category_path: string;\n    is_representative: boolean;\n    kosis_url: string;\n    latest_period?: string;\n  }[];\n  raw_meta: any;\n}\n",
  "src/utils/logger.ts": "const ts = () => new Date().toISOString().replace('T', ' ').slice(0, 19);\n\nexport const log = {\n  info: (msg: string, extra?: unknown) => {\n    console.log(`[${ts()}] i  ${msg}${extra ? ' ' + JSON.stringify(extra) : ''}`);\n  },\n  ok: (msg: string, extra?: unknown) => {\n    console.log(`[${ts()}] OK ${msg}${extra ? ' ' + JSON.stringify(extra) : ''}`);\n  },\n  warn: (msg: string, extra?: unknown) => {\n    console.warn(`[${ts()}] !  ${msg}${extra ? ' ' + JSON.stringify(extra) : ''}`);\n  },\n  err: (msg: string, error?: unknown) => {\n    console.error(`[${ts()}] X  ${msg}${error ? ' ' + String(error) : ''}`);\n  },\n};\n",
  "src/clients/kosis.ts": "import 'dotenv/config';\nimport type { KosisListItem, KosisTableMeta } from '../types.js';\n\nconst BASE = 'https://kosis.kr/openapi';\nconst API_KEY = process.env.KOSIS_API_KEY;\n\nif (!API_KEY) throw new Error('KOSIS_API_KEY is required in .env');\n\nasync function kosisFetch<T>(endpoint: string, params: Record<string, string>, retries = 3): Promise<T> {\n  const url = new URL(`${BASE}/${endpoint}`);\n  url.searchParams.set('apiKey', API_KEY!);\n  url.searchParams.set('format', 'json');\n  url.searchParams.set('jsonVD', 'Y');\n  for (const [k, v] of Object.entries(params)) url.searchParams.set(k, v);\n\n  for (let attempt = 0; attempt <= retries; attempt++) {\n    try {\n      const res = await fetch(url.toString());\n      if (!res.ok) throw new Error(`HTTP ${res.status}`);\n      const data = await res.json();\n      if (data && typeof data === 'object' && 'err' in data) {\n        const errCode = String((data as any).err);\n        if (['10', '30', '-30'].includes(errCode)) {\n          throw new Error(`KOSIS error [${errCode}]: ${(data as any).errMsg}`);\n        }\n        throw new Error(`KOSIS transient [${errCode}]: ${(data as any).errMsg}`);\n      }\n      return data as T;\n    } catch (e: any) {\n      if (attempt === retries) throw e;\n      await new Promise(r => setTimeout(r, 500 * Math.pow(2, attempt)));\n    }\n  }\n  throw new Error('unreachable');\n}\n\nexport function fetchListByOrg(parentListId?: string) {\n  const p: Record<string, string> = { method: 'getList', vwCd: 'MT_OTITLE' };\n  if (parentListId) p.parentListId = parentListId;\n  return kosisFetch<KosisListItem[]>('statisticsList.do', p);\n}\n\nexport function fetchListByTopic(parentListId?: string) {\n  const p: Record<string, string> = { method: 'getList', vwCd: 'MT_ZTITLE' };\n  if (parentListId) p.parentListId = parentListId;\n  return kosisFetch<KosisListItem[]>('statisticsList.do', p);\n}\n\nexport function fetchTableMeta(orgId: string, tblId: string) {\n  return kosisFetch<KosisTableMeta[]>('statisticsList.do', {\n    method: 'getMeta', orgId, tblId, type: 'TBL'\n  });\n}\n",
  "src/clients/supabase.ts": "import 'dotenv/config';\nimport { createClient } from '@supabase/supabase-js';\n\nconst url = process.env.SUPABASE_URL;\nconst serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;\n\nif (!url || !serviceKey) {\n  throw new Error('SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required in .env');\n}\n\nexport const supabase = createClient(url, serviceKey, {\n  auth: { autoRefreshToken: false, persistSession: false },\n});\n",
  "src/seed/01_fetchTables.ts": "/**\n * KOSIS 국가데이터처(orgId=101) 통계표 전수 수집\n */\nimport { writeFileSync, mkdirSync } from 'node:fs';\nimport { fetchListByTopic } from '../clients/kosis.js';\nimport type { CollectedTable, KosisListItem } from '../types.js';\nimport { log } from '../utils/logger.js';\nimport pLimit from 'p-limit';\n\nconst OUT_DIR = 'data/seed';\nconst OUT_FILE = `${OUT_DIR}/01_tables.json`;\nconst ORG_ID = process.env.KOSIS_ORG_ID ?? '101';\nconst CONCURRENCY = Number(process.env.SEED_CONCURRENCY ?? '3');\nconst MAX_DEPTH = 6;\n\nconst limit = pLimit(CONCURRENCY);\nconst collected: CollectedTable[] = [];\nconst visited = new Set<string>();\n\nasync function walk(listId: string | undefined, crumbs: string[], depth: number) {\n  if (depth > MAX_DEPTH) { log.warn(`max depth at ${crumbs.join(' > ')}`); return; }\n  if (listId && visited.has(listId)) return;\n  if (listId) visited.add(listId);\n\n  let items: KosisListItem[] = [];\n  try { items = await fetchListByTopic(listId); }\n  catch (e: any) { log.err(`fetch failed at ${crumbs.join(' > ')}`, e.message); return; }\n\n  if (!Array.isArray(items)) { log.warn(`non-array at ${crumbs.join(' > ')}`); return; }\n\n  const tables = items.filter(it => it.TBL_ID);\n  const categories = items.filter(it => !it.TBL_ID && it.LIST_ID);\n\n  for (const t of tables) {\n    if (t.ORG_ID !== ORG_ID) continue;\n    collected.push({\n      org_id: t.ORG_ID!,\n      tbl_id: t.TBL_ID!,\n      tbl_nm: t.TBL_NM ?? '',\n      stat_nm: t.STAT_NM ?? '',\n      category_path: crumbs.join(' > '),\n      full_path_id: t.FULL_PATH_ID,\n      link_url: t.LINK_URL,\n    });\n  }\n\n  await Promise.all(categories.map(cat =>\n    limit(() => walk(cat.LIST_ID, [...crumbs, cat.LIST_NM ?? '?'], depth + 1))\n  ));\n}\n\nasync function main() {\n  mkdirSync(OUT_DIR, { recursive: true });\n  log.info(`Start crawling (org=${ORG_ID}, concurrency=${CONCURRENCY})`);\n  const t0 = Date.now();\n  await walk(undefined, [], 0);\n  const elapsed = ((Date.now() - t0) / 1000).toFixed(1);\n\n  const dedup = new Map<string, CollectedTable>();\n  for (const t of collected) {\n    const key = `${t.org_id}:${t.tbl_id}`;\n    if (!dedup.has(key)) dedup.set(key, t);\n  }\n  const final = [...dedup.values()];\n  writeFileSync(OUT_FILE, JSON.stringify(final, null, 2), 'utf-8');\n  log.ok(`Collected ${final.length} tables in ${elapsed}s -> ${OUT_FILE}`);\n\n  const byStat = new Map<string, number>();\n  for (const t of final) byStat.set(t.stat_nm, (byStat.get(t.stat_nm) ?? 0) + 1);\n  log.info(`Unique statistics: ${byStat.size}`);\n  log.info(`Top 10 by table count:`);\n  [...byStat.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10)\n    .forEach(([n,c]) => console.log(`   ${String(c).padStart(4)}  ${n}`));\n}\n\nmain().catch(e => { log.err('Fatal', e); process.exit(1); });\n",
  "src/seed/02_fetchMeta.ts": "/**\n * 각 통계표의 메타를 병렬 조회\n */\nimport { readFileSync, writeFileSync } from 'node:fs';\nimport pLimit from 'p-limit';\nimport { fetchTableMeta } from '../clients/kosis.js';\nimport type { CollectedTable, EnrichedTable } from '../types.js';\nimport { log } from '../utils/logger.js';\n\nconst IN_FILE = 'data/seed/01_tables.json';\nconst OUT_FILE = 'data/seed/02_meta.json';\nconst CONCURRENCY = Number(process.env.SEED_CONCURRENCY ?? '3');\n\nasync function main() {\n  const tables: CollectedTable[] = JSON.parse(readFileSync(IN_FILE, 'utf-8'));\n  log.info(`Loaded ${tables.length} tables. Fetching meta (concurrency=${CONCURRENCY})`);\n\n  const t0 = Date.now();\n  const limit = pLimit(CONCURRENCY);\n  let done = 0, failed = 0;\n\n  const enriched = await Promise.all(tables.map(t => limit(async () => {\n    const out: EnrichedTable = { ...t };\n    try {\n      const metaArr = await fetchTableMeta(t.org_id, t.tbl_id);\n      out.meta = Array.isArray(metaArr) && metaArr.length > 0 ? metaArr[0] : undefined;\n    } catch (e: any) { out.meta_error = e.message; failed++; }\n    finally {\n      done++;\n      if (done % 20 === 0) log.info(`Progress ${done}/${tables.length} (failed=${failed})`);\n    }\n    return out;\n  })));\n\n  const elapsed = ((Date.now() - t0) / 1000).toFixed(1);\n  writeFileSync(OUT_FILE, JSON.stringify(enriched, null, 2), 'utf-8');\n  log.ok(`Enriched ${enriched.length - failed}/${enriched.length} in ${elapsed}s -> ${OUT_FILE}`);\n  if (failed > 0) log.warn(`${failed} tables failed`);\n}\n\nmain().catch(e => { log.err('Fatal', e); process.exit(1); });\n",
  "src/seed/03_buildStatistics.ts": "/**\n * 통계표를 조사(statistic) 단위로 그룹핑\n */\nimport { readFileSync, writeFileSync } from 'node:fs';\nimport type { EnrichedTable, BuiltStatistic } from '../types.js';\nimport { log } from '../utils/logger.js';\n\nconst IN_FILE = 'data/seed/02_meta.json';\nconst OUT_FILE = 'data/seed/03_statistics.json';\n\nfunction toStatId(name: string): string {\n  return name.trim().replace(/[^\\p{L}\\p{N}]+/gu, '_').replace(/^_+|_+$/g, '').toLowerCase();\n}\nfunction topCategory(path: string): string {\n  return path.split(' > ')[0] ?? '';\n}\n\nfunction main() {\n  const enriched: EnrichedTable[] = JSON.parse(readFileSync(IN_FILE, 'utf-8'));\n  log.info(`Building statistics from ${enriched.length} tables`);\n\n  const groups = new Map<string, EnrichedTable[]>();\n  for (const t of enriched) {\n    if (!t.stat_nm) continue;\n    if (!groups.has(t.stat_nm)) groups.set(t.stat_nm, []);\n    groups.get(t.stat_nm)!.push(t);\n  }\n\n  const built: BuiltStatistic[] = [];\n  for (const [statNm, ts] of groups) {\n    const sorted = [...ts].sort((a,b) => a.category_path.length - b.category_path.length);\n    const rep = sorted[0];\n    const meta = rep.meta;\n    built.push({\n      stat_id: toStatId(statNm),\n      stat_nm: statNm,\n      agency: meta?.MAINC_NM ?? '국가데이터처',\n      org_id: rep.org_id,\n      category: topCategory(rep.category_path),\n      legal_basis: meta?.LAWFUL_BAS,\n      purpose: meta?.PRP_CNT,\n      target: meta?.STATS_TARGET,\n      method: meta?.RESN_TXT,\n      frequency: meta?.COLLECT_CYCLE,\n      tables: ts.map(t => ({\n        kosis_org_id: t.org_id,\n        kosis_tbl_id: t.tbl_id,\n        table_name: t.tbl_nm,\n        category_path: t.category_path,\n        is_representative: t === rep,\n        kosis_url: t.link_url || `https://kosis.kr/statHtml/statHtml.do?orgId=${t.org_id}&tblId=${t.tbl_id}&conn_path=I3`,\n        latest_period: t.meta?.END_PRD_DE,\n      })),\n      raw_meta: meta ?? null,\n    });\n  }\n  built.sort((a,b) => a.stat_nm.localeCompare(b.stat_nm, 'ko'));\n\n  writeFileSync(OUT_FILE, JSON.stringify(built, null, 2), 'utf-8');\n  log.ok(`Built ${built.length} statistics -> ${OUT_FILE}`);\n\n  const byCat = new Map<string, number>();\n  for (const s of built) byCat.set(s.category, (byCat.get(s.category) ?? 0) + 1);\n  log.info(`By category:`);\n  [...byCat.entries()].sort((a,b)=>b[1]-a[1])\n    .forEach(([c,n]) => console.log(`   ${String(n).padStart(3)}  ${c}`));\n}\n\nmain();\n",
  "src/seed/04_upsertSupabase.ts": "/**\n * Supabase 배치 upsert (재실행 안전)\n */\nimport { readFileSync } from 'node:fs';\nimport { supabase } from '../clients/supabase.js';\nimport type { BuiltStatistic } from '../types.js';\nimport { log } from '../utils/logger.js';\n\nconst IN_FILE = 'data/seed/03_statistics.json';\nconst BATCH = 100;\n\nasync function main() {\n  const stats: BuiltStatistic[] = JSON.parse(readFileSync(IN_FILE, 'utf-8'));\n  log.info(`Upserting ${stats.length} statistics`);\n\n  const statRows = stats.map(s => ({\n    stat_id: s.stat_id, name_ko: s.stat_nm, agency: s.agency, org_id: s.org_id,\n    category: s.category, legal_basis: s.legal_basis, purpose: s.purpose,\n    target: s.target, method: s.method, frequency: s.frequency,\n    raw_meta: s.raw_meta, status: 'active',\n  }));\n\n  for (let i = 0; i < statRows.length; i += BATCH) {\n    const batch = statRows.slice(i, i + BATCH);\n    const { error } = await supabase.from('statistics').upsert(batch, { onConflict: 'stat_id' });\n    if (error) { log.err(`stats batch ${i} failed`, error); throw error; }\n    log.info(`Statistics: ${Math.min(i + BATCH, statRows.length)}/${statRows.length}`);\n  }\n  log.ok(`All statistics upserted`);\n\n  const { data: statMap, error: mapErr } = await supabase.from('statistics').select('id, stat_id');\n  if (mapErr) throw mapErr;\n  const idByStatId = new Map(statMap!.map(r => [r.stat_id, r.id]));\n\n  const tableRows: any[] = [];\n  for (const s of stats) {\n    const uuid = idByStatId.get(s.stat_id);\n    if (!uuid) { log.warn(`missing uuid for ${s.stat_id}`); continue; }\n    s.tables.forEach((t, idx) => tableRows.push({\n      statistic_id: uuid, kosis_org_id: t.kosis_org_id, kosis_tbl_id: t.kosis_tbl_id,\n      table_name: t.table_name, category_path: t.category_path,\n      is_representative: t.is_representative, display_order: idx,\n      kosis_url: t.kosis_url, latest_period: t.latest_period,\n    }));\n  }\n\n  for (let i = 0; i < tableRows.length; i += BATCH) {\n    const batch = tableRows.slice(i, i + BATCH);\n    const { error } = await supabase.from('statistic_tables').upsert(batch, { onConflict: 'kosis_org_id,kosis_tbl_id' });\n    if (error) { log.err(`tables batch ${i} failed`, error); throw error; }\n    log.info(`Tables: ${Math.min(i + BATCH, tableRows.length)}/${tableRows.length}`);\n  }\n\n  const { count: sc } = await supabase.from('statistics').select('*', { count: 'exact', head: true });\n  const { count: tc } = await supabase.from('statistic_tables').select('*', { count: 'exact', head: true });\n  log.ok(`Final: ${sc} statistics, ${tc} tables in Supabase`);\n}\n\nmain().catch(e => { log.err('Fatal', e); process.exit(1); });\n"
};

let created = 0, skipped = 0;
for (const [path, content] of Object.entries(files)) {
  const dir = dirname(path);
  if (dir && dir !== '.') mkdirSync(dir, { recursive: true });
  if (existsSync(path)) {
    console.log('  skip    ' + path);
    skipped++;
    continue;
  }
  writeFileSync(path, content, 'utf-8');
  console.log('  create  ' + path);
  created++;
}

console.log('');
console.log('Done. created=' + created + ', skipped=' + skipped);
console.log('');
console.log('Next steps:');
console.log('  1) cp .env.example .env  (then fill in values)');
console.log('  2) pnpm install   (or npm install)');
console.log('  3) pnpm seed:tables');
console.log('  4) pnpm seed:meta');
console.log('  5) pnpm seed:build');
console.log('  6) pnpm seed:upsert');
